BATCH_SIZE: 1
CLASSES:
- face
DATASET:
  AUGMENTOR: !!python/object:blueoil.data_processor.Sequence
    processors:
    - !!python/object:blueoil.data_augmentor.FlipLeftRight
      probability: 0.5
    - !!python/object:blueoil.data_augmentor.Brightness
      max_value: 1.25
      min_value: 0.75
    - !!python/object:blueoil.data_augmentor.Color
      max_value: 1.25
      min_value: 0.75
    - !!python/object:blueoil.data_augmentor.Contrast
      max_value: 1.25
      min_value: 0.75
    - !!python/object:blueoil.data_augmentor.Hue
      max_value: 10
      min_value: -10
    - !!python/object:blueoil.data_augmentor.SSDRandomCrop
      aspect_ratio_max: 2
      aspect_ratio_min: 0.5
      min_crop_ratio: 0.5
      sample_options: !!python/tuple
      - null
      - !!python/tuple
        - 0.1
        - null
      - !!python/tuple
        - 0.3
        - null
      - !!python/tuple
        - 0.7
        - null
      - !!python/tuple
        - 0.9
        - null
      - !!python/tuple
        - null
        - null
  BATCH_SIZE: 1
  DATA_FORMAT: NHWC
  ENABLE_PREFETCH: true
  PRE_PROCESSOR: !!python/object:blueoil.data_processor.Sequence
    processors:
    - !!python/object:lmnet.pre_processor.ResizeWithGtBoxes
      size:
      - 160
      - 160
    - !!python/object:lmnet.pre_processor.DivideBy255 {}
DATASET_CLASS: !!python/name:blueoil.datasets.widerface.WiderFace ''
DATA_FORMAT: NHWC
IMAGE_SIZE:
- 160
- 160
IS_DEBUG: false
IS_PRETRAIN: true
KEEP_CHECKPOINT_MAX: 5
MAX_STEPS: 1000000
NETWORK:
  ACTIVATION_QUANTIZER: !!python/name:lmnet.quantizations.linear.linear_mid_tread_half_quantizer ''
  ACTIVATION_QUANTIZER_KWARGS:
    bit: 2
    max_value: 2.0
  ANCHORS:
  - !!python/tuple
    - 0.25
    - 0.25
  - !!python/tuple
    - 0.5
    - 0.5
  - !!python/tuple
    - 1.0
    - 1.0
  - !!python/tuple
    - 1.5
    - 1.5
  - !!python/tuple
    - 2.0
    - 2.0
  BATCH_SIZE: 1
  CLASS_SCALE: 1.0
  COORDINATE_SCALE: 1.0
  DATA_FORMAT: NHWC
  IMAGE_SIZE:
  - 160
  - 160
  LEARNING_RATE_FUNC: !!python/name:tensorflow.python.training.learning_rate_decay.piecewise_constant ''
  LEARNING_RATE_KWARGS:
    boundaries:
    - 258
    - 20640
    - 30960
    values:
    - 0.0005
    - 0.02
    - 0.005
    - 0.0005
  LOSS_IOU_THRESHOLD: 0.6
  LOSS_WARMUP_STEPS: 8000
  NMS_IOU_THRESHOLD: 0.5
  NMS_MAX_OUTPUT_SIZE: 100
  NO_OBJECT_SCALE: 1.0
  OBJECT_SCALE: 5.0
  OPTIMIZER_CLASS: !!python/name:tensorflow.python.training.momentum.MomentumOptimizer ''
  OPTIMIZER_KWARGS:
    momentum: 0.9
  QUANTIZE_FIRST_CONVOLUTION: true
  QUANTIZE_LAST_CONVOLUTION: false
  SCORE_THRESHOLD: 0.05
  WEIGHT_DECAY_RATE: 0.0005
  WEIGHT_QUANTIZER: !!python/name:lmnet.quantizations.binary.binary_channel_wise_mean_scaling_quantizer ''
  WEIGHT_QUANTIZER_KWARGS: {}
NETWORK_CLASS: !!python/name:blueoil.networks.object_detection.lm_fyolo.LMFYoloQuantize ''
NMS: !!python/name:lmnet.post_processor.NMS ''
POST_PROCESSOR: !!python/object:blueoil.data_processor.Sequence
  processors:
  - !!python/object:lmnet.post_processor.FormatYoloV2
    anchors:
    - !!python/tuple
      - 0.25
      - 0.25
    - !!python/tuple
      - 0.5
      - 0.5
    - !!python/tuple
      - 1.0
      - 1.0
    - !!python/tuple
      - 1.5
      - 1.5
    - !!python/tuple
      - 2.0
      - 2.0
    boxes_per_cell: 5
    data_format: NHWC
    image_size:
    - 160
    - 160
    num_classes: 1
  - !!python/object:lmnet.post_processor.ExcludeLowScoreBox
    threshold: 0.05
  - !!python/object:lmnet.post_processor.NMS
    classes:
    - face
    iou_threshold: 0.5
    max_output_size: 100
    per_class: true
PRETRAIN_DIR: /storage/lmnet/saved/core/object_detection/lm_fyolo_quantize_pascalvoc_2007_2012/checkpoints
PRETRAIN_FILE: save.ckpt-70000
PRETRAIN_VARS:
- block_1/conv/kernel:0
- block_1/bn/beta:0
- block_1/bn/gamma:0
- block_1/bn/moving_mean:0
- block_1/bn/moving_variance:0
- block_2/conv/kernel:0
- block_2/bn/beta:0
- block_2/bn/gamma:0
- block_2/bn/moving_mean:0
- block_2/bn/moving_variance:0
- block_3/conv/kernel:0
- block_3/bn/beta:0
- block_3/bn/gamma:0
- block_3/bn/moving_mean:0
- block_3/bn/moving_variance:0
- block_4/conv/kernel:0
- block_4/bn/beta:0
- block_4/bn/gamma:0
- block_4/bn/moving_mean:0
- block_4/bn/moving_variance:0
- block_5/conv/kernel:0
- block_5/bn/beta:0
- block_5/bn/gamma:0
- block_5/bn/moving_mean:0
- block_5/bn/moving_variance:0
- block_6/conv/kernel:0
- block_6/bn/beta:0
- block_6/bn/gamma:0
- block_6/bn/moving_mean:0
- block_6/bn/moving_variance:0
- block_4_1x1/conv/kernel:0
- block_4_1x1/bn/beta:0
- block_4_1x1/bn/gamma:0
- block_4_1x1/bn/moving_mean:0
- block_4_1x1/bn/moving_variance:0
- block_5_1x1/conv/kernel:0
- block_5_1x1/bn/beta:0
- block_5_1x1/bn/gamma:0
- block_5_1x1/bn/moving_mean:0
- block_5_1x1/bn/moving_variance:0
- block_6_1x1/conv/kernel:0
- block_6_1x1/bn/beta:0
- block_6_1x1/bn/gamma:0
- block_6_1x1/bn/moving_mean:0
- block_6_1x1/bn/moving_variance:0
- block_7/conv/kernel:0
- block_7/bn/beta:0
- block_7/bn/gamma:0
- block_7/bn/moving_mean:0
- block_7/bn/moving_variance:0
- block_8/conv/kernel:0
- block_8/bn/beta:0
- block_8/bn/gamma:0
- block_8/bn/moving_mean:0
- block_8/bn/moving_variance:0
- block_9/conv/kernel:0
- block_9/bn/beta:0
- block_9/bn/gamma:0
- block_9/bn/moving_mean:0
- block_9/bn/moving_variance:0
- block_10/conv/kernel:0
- block_10/bn/beta:0
- block_10/bn/gamma:0
- block_10/bn/moving_mean:0
- block_10/bn/moving_variance:0
- block_11/conv/kernel:0
- block_11/bn/beta:0
- block_11/bn/gamma:0
- block_11/bn/moving_mean:0
- block_11/bn/moving_variance:0
- block_12/conv/kernel:0
- block_12/bn/beta:0
- block_12/bn/gamma:0
- block_12/bn/moving_mean:0
- block_12/bn/moving_variance:0
- block_13/conv/kernel:0
- block_13/bn/beta:0
- block_13/bn/gamma:0
- block_13/bn/moving_mean:0
- block_13/bn/moving_variance:0
PRE_PROCESSOR: !!python/object:blueoil.data_processor.Sequence
  processors:
  - !!python/object:lmnet.pre_processor.ResizeWithGtBoxes
    size:
    - 160
    - 160
  - !!python/object:lmnet.pre_processor.DivideBy255 {}
SAVE_CHECKPOINT_STEPS: 1000
SUMMARISE_STEPS: 1000
TASK: !!python/object/apply:lmnet.common.Tasks
- IMAGE.OBJECT_DETECTION
TEST_STEPS: 1000
