# supported task types are 'classification', 'object_detection' and 'semantic_segmentation'.
task_type: {{ task_type }}

network_name: {{ network_name }}

dataset:
  format: {{ dataset_format }}
  train_path: {{ train_path }}
  test_path: {{ test_path }}

trainer:
  batch_size: {{ batch_size }}
  epochs: {{ training_epochs }}
# supported 'optimizer' is 'Momentum', 'SGD', 'Adam' currently.
  optimizer: {{ training_optimizer }}
# supported 'learning_rate_setting' is 'tune1', 'tune2', 'tune3', 'fixed'.
#   'tune1' is 2 times decay, learning rate reduce to 1/10 on epoch/2 and epoch-1.
#   'tune2' is 3 times decay, learning rate reduce to 1/10 on epoch/3 and epoch*2/3 and epoch-1.
#   'tune3' is warmup and 3 times decay, warmup learning rate 1/1000 in 1 epoch, then train same as 'tune2'.
#   'fixed' is constant learning rate.
  learning_rate_setting: {{ training_learning_rate_setting }}
  initial_learning_rate: {{ initial_learning_rate_value }}

network:
  quantize_first_convolution: {{ quantize_first_convolution }}

common:
  image_size:
    - {{ image_size[0] }}  # height
    - {{ image_size[1] }}  # width

  # set pretrain model name. currently, this feature is not supported, always ignored.
  pretrain_model: false

  # enable dataset prefetch, set false if weired problem happens
  dataset_prefetch: true
