BATCH_SIZE: 8
CLASSES:
- hand
- salad
- steak
- whiskey
- book
DATASET:
  AUGMENTOR: !!python/object:lmnet.data_processor.Sequence
    processors:
    - !!python/object:lmnet.data_augmentor.FlipLeftRight
      probability: 0.5
    - !!python/object:lmnet.data_augmentor.Brightness
      max_value: 1.25
      min_value: 0.75
    - !!python/object:lmnet.data_augmentor.Color
      max_value: 1.25
      min_value: 0.75
    - !!python/object:lmnet.data_augmentor.Contrast
      max_value: 1.25
      min_value: 0.75
    - !!python/object:lmnet.data_augmentor.Hue
      max_value: 10
      min_value: -10
    - !!python/object:lmnet.data_augmentor.SSDRandomCrop
      aspect_ratio_max: 2
      aspect_ratio_min: 0.5
      min_crop_ratio: 0.7
      sample_options: !!python/tuple
      - null
      - !!python/tuple
        - 0.1
        - null
      - !!python/tuple
        - 0.3
        - null
      - !!python/tuple
        - 0.7
        - null
      - !!python/tuple
        - 0.9
        - null
      - !!python/tuple
        - null
        - null
  BATCH_SIZE: 8
  DATA_FORMAT: NCHW
  PRE_PROCESSOR: !!python/object:lmnet.data_processor.Sequence
    processors:
    - !!python/object:lmnet.pre_processor.ResizeWithGtBoxes
      size:
      - 128
      - 128
    - !!python/object:lmnet.pre_processor.DivideBy255 {}
DATASET_CLASS: !!python/name:lmnet.datasets.open_images_v4.OpenImagesV4BoundingBox ''
DATA_FORMAT: NCHW
IMAGE_SIZE:
- 128
- 128
IS_DEBUG: false
IS_PRETRAIN: false
KEEP_CHECKPOINT_MAX: 5
MAX_EPOCHS: 1
NETWORK:
  ACTIVATION_QUANTIZER: !!python/name:lmnet.quantizations.linear.linear_mid_tread_half_quantizer ''
  ACTIVATION_QUANTIZER_KWARGS:
    bit: 2
    max_value: 2.0
  ANCHORS:
  - !!python/tuple
    - 1.3221
    - 1.73145
  - !!python/tuple
    - 3.19275
    - 4.00944
  - !!python/tuple
    - 5.05587
    - 8.09892
  - !!python/tuple
    - 9.47112
    - 4.84053
  - !!python/tuple
    - 11.2364
    - 10.0071
  BATCH_SIZE: 8
  CLASS_SCALE: 1.0
  COORDINATE_SCALE: 1.0
  DATA_FORMAT: NCHW
  IMAGE_SIZE:
  - 128
  - 128
  LEARNING_RATE_FUNC: !!python/name:tensorflow.python.training.learning_rate_decay.piecewise_constant ''
  LEARNING_RATE_KWARGS:
    boundaries:
    - 2068
    - 20680
    - 124080
    - 186120
    values:
    - 1.0e-06
    - 0.0001
    - 1.0e-05
    - 1.0e-06
    - 1.0e-07
  LOSS_IOU_THRESHOLD: 0.6
  LOSS_WARMUP_STEPS: 160
  NMS_IOU_THRESHOLD: 0.5
  NMS_MAX_OUTPUT_SIZE: 100
  NO_OBJECT_SCALE: 1.0
  OBJECT_SCALE: 5.0
  OPTIMIZER_CLASS: !!python/name:tensorflow.python.training.momentum.MomentumOptimizer ''
  OPTIMIZER_KWARGS:
    momentum: 0.9
  QUANTIZE_FIRST_CONVOLUTION: true
  QUANTIZE_LAST_CONVOLUTION: false
  SCORE_THRESHOLD: 0.05
  WEIGHT_DECAY_RATE: 0.0005
  WEIGHT_QUANTIZER: !!python/name:lmnet.quantizations.binary.binary_channel_wise_mean_scaling_quantizer ''
  WEIGHT_QUANTIZER_KWARGS: {}
NETWORK_CLASS: !!python/name:lmnet.networks.object_detection.yolo_v2_quantize.YoloV2Quantize ''
NMS: !!python/name:lmnet.post_processor.NMS ''
POST_PROCESSOR: !!python/object:lmnet.data_processor.Sequence
  processors:
  - !!python/object:lmnet.post_processor.FormatYoloV2
    anchors:
    - !!python/tuple
      - 1.3221
      - 1.73145
    - !!python/tuple
      - 3.19275
      - 4.00944
    - !!python/tuple
      - 5.05587
      - 8.09892
    - !!python/tuple
      - 9.47112
      - 4.84053
    - !!python/tuple
      - 11.2364
      - 10.0071
    boxes_per_cell: 5
    data_format: NCHW
    image_size:
    - 128
    - 128
    num_classes: 5
  - !!python/object:lmnet.post_processor.ExcludeLowScoreBox
    threshold: 0.05
  - !!python/object:lmnet.post_processor.NMS
    classes:
    - hand
    - salad
    - steak
    - whiskey
    - book
    iou_threshold: 0.5
    max_output_size: 100
    per_class: true
PRETRAIN_DIR: ''
PRETRAIN_FILE: ''
PRETRAIN_VARS: []
PRE_PROCESSOR: !!python/object:lmnet.data_processor.Sequence
  processors:
  - !!python/object:lmnet.pre_processor.ResizeWithGtBoxes
    size:
    - 128
    - 128
  - !!python/object:lmnet.pre_processor.DivideBy255 {}
SAVE_CHECKPOINT_STEPS: 100
SUMMARISE_STEPS: 10
TASK: !!python/object/apply:lmnet.common.Tasks
- IMAGE.OBJECT_DETECTION
TEST_STEPS: 100
